sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating"
  - docker build -t pianist5555/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true pianist5555/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"
       


