sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating"
  - docker build -t pianist5555/docker-react-app -f Dockerfile.dev .

    #script:
    #- docker run -e CI=true pianist5555/docker-react-app 

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-605592615509"
  bucket_path: "docker-react-app"
  on:
    branch: master 

access_key_id: $AWS_Access_key
secret_access_key: $AWS_Secret_Access_key
